TERMINALS = ["0", "1", "a", "b"]
INPUT_STR = ["0", "a", "a", "a", "1"]
# INPUT_STR = ["0", "1"]
# INPUT_STR = ["b"]
# INPUT_STR = ["0", "a", "b", "1"]
# INPUT_STR = ["0", "b"]
# INPUT_STR = ["0", "a", "a", "c", "1"]